language: ruby

services:
   - docker

before_install:
   - bundle install
   - gem install rspec selenium-webdriver
   - sudo gem update –system
   - gem list selenium-webdriver rspec
   - docker build -t selenium/standalone-chrome .
   - docker run -d -p 4444:4444 selenium/standalone-chrome
   - docker images
   - docker ps
