language: ruby

services:
   - docker

before_install:
   - sudo gem update –system
   - docker build -t selenium/standalone-chrome .
   - docker run -d -p 4444:4444 selenium/standalone-chrome

script:
   - ruby browser_test.rb
