language: ruby

services:
   - docker

before_install:
   - bundle install
   - sudo gem install selenium-webdriver rspec
   - docker build -t selenium/standalone-chrome .
   - docker run -d -p 4444:4444 selenium/standalone-chrome

script:
   - ruby browser_test.rb
